### PR TITLE
Check that discussion/post still exists before attempting to notify

### LINKED ISSUE #13: Incompatible with FoF Filter
Hello, auto merge does not work when follow tags is enabled.
Here is the error:

```{
  "errors": [
    {
      "status": "404",
      "code": "not_found",
      "detail": "Illuminate\\Database\\Eloquent\\ModelNotFoundException: No query results for model [Flarum\\Post\\CommentPost]. in /var/www/html/playcb.eu/forum/vendor/illuminate/database/Eloquent/Builder.php:452\nStack trace:\n#0 /var/www/html/playcb.eu/forum/vendor/illuminate/queue/SerializesAndRestoresModelIdentifiers.php(85): Illuminate\\Database\\Eloquent\\Builder->firstOrFail()\n#1 /var/www/html/playcb.eu/forum/vendor/illuminate/queue/SerializesAndRestoresModelIdentifiers.php(55): FoF\\FollowTags\\Jobs\\SendNotificationWhenReplyIsPosted->restoreModel()\n#2 /var/www/html/playcb.eu/forum/vendor/illuminate/queue/SerializesModels.php(45): FoF\\FollowTags\\Jobs\\SendNotificationWhenReplyIsPosted->getRestoredPropertyValue()\n#3 [internal function]: FoF\\FollowTags\\Jobs\\SendNotificationWhenReplyIsPosted->__wakeup()\n#4 /var/www/html/playcb.eu/forum/vendor/illuminate/queue/CallQueuedHandler.php(146): unserialize()\n#5 /var/www/html/playcb.eu/forum/vendor/illuminate/queue/Jobs/Job.php(172): Illuminate\\Queue\\CallQueuedHandler->failed()\n#6 /var/www/html/playcb.eu/forum/vendor/illuminate/queue/FailingJob.php(33): Illuminate\\Queue\\Jobs\\Job->failed()\n#7 /var/www/html/playcb.eu/forum/vendor/illuminate/queue/CallQueuedHandler.php(131): Illuminate\\Queue\\FailingJob::handle()\n#8 /var/www/html/playcb.eu/forum/vendor/illuminate/queue/CallQueuedHandler.php(45): Illuminate\\Queue\\CallQueuedHandler->handleModelNotFound()\n#9 /var/www/html/playcb.eu/forum/vendor/illuminate/queue/Jobs/Job.php(83): Illuminate\\Queue\\CallQueuedHandler->call()\n#10 /var/www/html/playcb.eu/forum/vendor/illuminate/queue/SyncQueue.php(42): Illuminate\\Queue\\Jobs\\Job->fire()\n#11 /var/www/html/playcb.eu/forum/vendor/fof/follow-tags/src/Listeners/QueueNotificationJobs.php(43): Illuminate\\Queue\\SyncQueue->push()\n#12 /var/www/html/playcb.eu/forum/vendor/illuminate/events/Dispatcher.php(360): FoF\\FollowTags\\Listeners\\QueueNotificationJobs->whenPostCreated()\n#13 /var/www/html/playcb.eu/forum/vendor/illuminate/events/Dispatcher.php(209): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()\n#14 /var/www/html/playcb.eu/forum/vendor/flarum/core/src/Foundation/DispatchEventsTrait.php(33): Illuminate\\Events\\Dispatcher->dispatch()\n#15 /var/www/html/playcb.eu/forum/vendor/flarum/core/src/Post/Command/PostReplyHandler.php(106): Flarum\\Post\\Command\\PostReplyHandler->dispatchEventsFor()\n#16 /var/www/html/playcb.eu/forum/vendor/flarum/core/src/Notification/NotificationSyncer.php(148): Flarum\\Post\\Command\\PostReplyHandler->Flarum\\Post\\Command\\{closure}()\n#17 /var/www/html/playcb.eu/forum/vendor/flarum/core/src/Post/Command/PostReplyHandler.php(107): Flarum\\Notification\\NotificationSyncer->onePerUser()\n#18 /var/www/html/playcb.eu/forum/vendor/illuminate/bus/Dispatcher.php(90): Flarum\\Post\\Command\\PostReplyHandler->handle()\n#19 /var/www/html/playcb.eu/forum/vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()\n#20 /var/www/html/playcb.eu/forum/vendor/illuminate/pipeline/Pipeline.php(104): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#21 /var/www/html/playcb.eu/forum/vendor/illuminate/bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()\n#22 /var/www/html/playcb.eu/forum/vendor/illuminate/bus/Dispatcher.php(76): Illuminate\\Bus\\Dispatcher->dispatchNow()\n#23 /var/www/html/playcb.eu/forum/vendor/flarum/core/src/Api/Controller/CreatePostController.php(73): Illuminate\\Bus\\Dispatcher->dispatch()\n#24 /var/www/html/playcb.eu/forum/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(96): Flarum\\Api\\Controller\\CreatePostController->data()\n#25 /var/www/html/playcb.eu/forum/vendor/flarum/core/src/Api/Controller/AbstractCreateController.php(22): Flarum\\Api\\Controller\\AbstractSerializeController->handle()\n#26 /var/www/html/playcb.eu/forum/vendor/flarum/core/src/Http/RouteHandlerFactory.php(38): Flarum\\Api\\Controller\\AbstractCreateController->handle()\n#27 /var/www/html/playcb.eu/forum/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(65): Flarum\\Http\\RouteHandlerFactory->Flarum\\Http\\{closure}()\n#28 /var/www/html/playcb.eu/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\\Http\\Middleware\\DispatchRoute->process()\n#29 /var/www/html/playcb.eu/forum/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Laminas\\Stratigility\\Next->handle()\n#30 /var/www/html/playcb.eu/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\\Http\\Middleware\\SetLocale->process()\n#31 /var/www/html/playcb.eu/forum/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(45): Laminas\\Stratigility\\Next->handle()\n#32 /var/www/html/playcb.eu/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\\Http\\Middleware\\CheckCsrfToken->process()\n#33 /var/www/html/playcb.eu/forum/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(55): Laminas\\Stratigility\\Next->handle()\n#34 /var/www/html/playcb.eu/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\\Http\\Middleware\\AuthenticateWithHeader->process()\n#35 /var/www/html/playcb.eu/forum/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(32): Laminas\\Stratigility\\Next->handle()\n#36 /var/www/html/playcb.eu/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\\Http\\Middleware\\AuthenticateWithSession->process()\n#37 /var/www/html/playcb.eu/forum/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(51): Laminas\\Stratigility\\Next->handle()\n#38 /var/www/html/playcb.eu/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\\Http\\Middleware\\RememberFromCookie->process()\n#39 /var/www/html/playcb.eu/forum/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\\Stratigility\\Next->handle()\n#40 /var/www/html/playcb.eu/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\\Http\\Middleware\\StartSession->process()\n#41 /var/www/html/playcb.eu/forum/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Laminas\\Stratigility\\Next->handle()\n#42 /var/www/html/playcb.eu/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\\Api\\Middleware\\FakeHttpMethods->process()\n#43 /var/www/html/playcb.eu/forum/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\\Stratigility\\Next->handle()\n#44 /var/www/html/playcb.eu/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\\Http\\Middleware\\ParseJsonBody->process()\n#45 /var/www/html/playcb.eu/forum/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\\Stratigility\\Next->handle()\n#46 /var/www/html/playcb.eu/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\\Http\\Middleware\\HandleErrors->process()\n#47 /var/www/html/playcb.eu/forum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\\Stratigility\\Next->handle()\n#48 /var/www/html/playcb.eu/forum/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\\Stratigility\\MiddlewarePipe->process()\n#49 /var/www/html/playcb.eu/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\\RequestHandler->process()\n#50 /var/www/html/playcb.eu/forum/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Laminas\\Stratigility\\Next->handle()\n#51 /var/www/html/playcb.eu/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\\BasePathRouter->process()\n#52 /var/www/html/playcb.eu/forum/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(42): Laminas\\Stratigility\\Next->handle()\n#53 /var/www/html/playcb.eu/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\\Stratigility\\Middleware\\OriginalMessages->process()\n#54 /var/www/html/playcb.eu/forum/vendor/middlewares/base-path/src/BasePath.php(53): Laminas\\Stratigility\\Next->handle()\n#55 /var/www/html/playcb.eu/forum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\\BasePath->process()\n#56 /var/www/html/playcb.eu/forum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\\Stratigility\\Next->handle()\n#57 /var/www/html/playcb.eu/forum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73): Laminas\\Stratigility\\MiddlewarePipe->process()\n#58 /var/www/html/playcb.eu/forum/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\\Stratigility\\MiddlewarePipe->handle()\n#59 /var/www/html/playcb.eu/forum/vendor/flarum/core/src/Http/Server.php(42): Laminas\\HttpHandlerRunner\\RequestHandlerRunner->run()\n#60 /var/www/html/playcb.eu/forum/public/index.php(26): Flarum\\Http\\Server->listen()\n#61 {main}"
    }
  ]
}
```

Please note, this error log is from a user on discuss.

Kind Regards

### PR DESCRIPTION
**Pull request by imorland**
Should close #13

### CODE REVIEW

**Comment by imorland** [comment]
@lukasdeveloper - this _should_ address the issue you're seeing. Before I merge it, would you mind cloning this branch/applying the patch of this PR and confirming?

**Comment by datitisev** [comment]
I do *not* think this will fix it. The error occurs when the Illuminate queue tries to retrieve the models from the DB, as the data that is passed to the Job queue is a model and not an ID, and we're telling it to store references to the model and not the model data itself.

```php
Illuminate\\Database\\Eloquent\\ModelNotFoundException: No query results for model [Flarum\\Post\\CommentPost]. in <forum>/vendor/illuminate/database/Eloquent/Builder.php:452
Stack trace:
#0 <forum>/vendor/illuminate/queue/SerializesAndRestoresModelIdentifiers.php(85): Illuminate\\Database\\Eloquent\\Builder->firstOrFail()
#1 <forum>/vendor/illuminate/queue/SerializesAndRestoresModelIdentifiers.php(55): FoF\\FollowTags\\Jobs\\SendNotificationWhenReplyIsPosted->restoreModel()
#2 <forum>/vendor/illuminate/queue/SerializesModels.php(45): FoF\\FollowTags\\Jobs\\SendNotificationWhenReplyIsPosted->getRestoredPropertyValue()
#3 [internal function]: FoF\\FollowTags\\Jobs\\SendNotificationWhenReplyIsPosted->__wakeup()
#4 <forum>/vendor/illuminate/queue/CallQueuedHandler.php(146): unserialize()
#5 <forum>/vendor/illuminate/queue/Jobs/Job.php(172): Illuminate\\Queue\\CallQueuedHandler->failed()
#6 <forum>/vendor/illuminate/queue/FailingJob.php(33): Illuminate\\Queue\\Jobs\\Job->failed()
#7 <forum>/vendor/illuminate/queue/CallQueuedHandler.php(131): Illuminate\\Queue\\FailingJob::handle()
#8 <forum>/vendor/illuminate/queue/CallQueuedHandler.php(45): Illuminate\\Queue\\CallQueuedHandler->handleModelNotFound()
#9 <forum>/vendor/illuminate/queue/Jobs/Job.php(83): Illuminate\\Queue\\CallQueuedHandler->call()
#10 <forum>/vendor/illuminate/queue/SyncQueue.php(42): Illuminate\\Queue\\Jobs\\Job->fire()
```

**Comment by lukasdeveloper** [comment]
> @lukasdeveloper - this _should_ address the issue you're seeing. Before I merge it, would you mind cloning this branch/applying the patch of this PR and confirming?

Hello,

How would I go about applying this patch? Sorry not too familiar.

Kind Regards

**Comment by datitisev** [comment]
@lukasdeveloper By running `composer require fof/follow-tags dev-im/filter`. I don't think this fixes the issue though.

**Comment by lukasdeveloper** [comment]
Thanks. @imorland this pr works fine :)

**Pull request merged**
