### PR TITLE
Add notification for discussion tag changed to a followed tag

### PR DESCRIPTION
**Pull request by imorland**
#8 

@datitisev mind taking a look over this for me please? Think I've covered it, but would appreciate a second set of eyes..

### CODE REVIEW

**Comment by datitisev** [comment]
Not sure if the code handles this, but don't send a notification if the previous tags where already followed & notified for? Not sure if possible. Just an idea.

**Comment by imorland** [comment]
So if a user has already received a notification for the moved discussion, the re-tagged notification won’t be applied by the sync, as the user already has it

**Comment by datitisev** [comment]
I think this is good. Nothing stands out to me. Haven't tested it locally.

**Comment by imorland** [comment]
Great, thanks 👍

**Pull request merged**
